name: return-that
recipe: laravel
config:
  php: '8.2'
  composer_version: 2
  webroot: public
#  database: mysql:8.0
proxy:
  mail:
    - mail.return-that.lndo.site
#  pma:
#    - pma.return-that.lndo.site
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get update -y
      - apt-get install -y cron nodejs
      - npm install --location=global yarn
      - yarn
    run_as_root:
      - service cron start
    run:
      - crontab /app/config/local/cron
    xdebug: true
    config:
      php: /app/config/local/php.ini
    ssl: true
    ports:
      - 24695
      - 24696
      - 24697
  mail:
    type: mailhog
    ssl: true
    hogfrom:
      - appserver
#  pma:
#    type: phpmyadmin
#    ssl: true
#    hosts:
#      - database
events:
  post-start:
    - printf "\033[0;31mDon't forget to run migrations and seed db!\033[0m\n"
tooling:
  node:
    service: appserver
  npx:
    service: appserver
  yarn:
    service: appserver
  dev:
    service: appserver
    description: Start vite dev server
    user: root
    cmd: yarn dev
